
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: ovirtcsioperators.ovirt.csidriver.openshift.io
  namespace: openshift-ovirt-infra
spec:
  group: ovirt.csidriver.openshift.io
  names:
    kind: OvirtCSIOperator
    listKind: OvirtCSIOperatorList
    plural: ovirtcsioperators
    singular: ovirtcsioperator
  scope: Namespaced
  subresources:
    status: {}
  validation:
    openAPIV3Schema:
      description: OvirtCSIOperator is the Schema for the ovirtcsioperators API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: OvirtCSIOperatorSpec defines the desired state of OvirtCSIOperator
          type: object
        status:
          description: OvirtCSIOperatorStatus defines the observed state of OvirtCSIOperator
          type: object
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
