kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: csi-operator
subjects:
- kind: ServiceAccount
  name: csi-operator
  namespace: openshift-ovirt-csi-operator
roleRef:
  kind: ClusterRole
  name: csi-operator
  apiGroup: rbac.authorization.k8s.io
