// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtCSIOperator) DeepCopyInto(out *OvirtCSIOperator) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtCSIOperator.
func (in *OvirtCSIOperator) DeepCopy() *OvirtCSIOperator {
	if in == nil {
		return nil
	}
	out := new(OvirtCSIOperator)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvirtCSIOperator) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtCSIOperatorList) DeepCopyInto(out *OvirtCSIOperatorList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]OvirtCSIOperator, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtCSIOperatorList.
func (in *OvirtCSIOperatorList) DeepCopy() *OvirtCSIOperatorList {
	if in == nil {
		return nil
	}
	out := new(OvirtCSIOperatorList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *OvirtCSIOperatorList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtCSIOperatorSpec) DeepCopyInto(out *OvirtCSIOperatorSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtCSIOperatorSpec.
func (in *OvirtCSIOperatorSpec) DeepCopy() *OvirtCSIOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(OvirtCSIOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OvirtCSIOperatorStatus) DeepCopyInto(out *OvirtCSIOperatorStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OvirtCSIOperatorStatus.
func (in *OvirtCSIOperatorStatus) DeepCopy() *OvirtCSIOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(OvirtCSIOperatorStatus)
	in.DeepCopyInto(out)
	return out
}
