apiVersion: cloudcredential.openshift.io/v1
kind: CredentialsRequest
metadata:
  name: ovirt-csi-driver
  namespace: openshift-cloud-credential-operator
spec:
  providerSpec:
    apiVersion: cloudcredential.openshift.io/v1
    kind: OvirtProviderSpec
  secretRef:
    name: ovirt-credentials
    namespace: openshift-ovirt-infra
