apiVersion: apps/v1
kind: Deployment
metadata:
  name: csi-operator
  namespace: openshift-ovirt-infra
spec:
  replicas: 1
  selector:
    matchLabels:
      name: csi-operator
  template:
    metadata:
      labels:
        name: csi-operator
    spec:
      serviceAccountName: csi-operator
      containers:
        - name: csi-operator
          # Replace this with the built image name
          image: quay.io/rgolangh/ovirt-csi-operator
          command:
          - csi-operator
          args:
            - "--v=5"
            - "--zap-devel"
          imagePullPolicy: Always
          env:
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: OPERATOR_NAME
              value: "csi-operator"
